apiVersion: v1
kind: Service
metadata:
  name: druid-overlord
  labels:
    app: druid
    component: overlord
spec:
  type: ClusterIP #NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      #nodePort: 30089
  selector:
    app: druid
    component: overlord
