apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  type: NodePort #ClusterIP
  ports:
  - name: jupyter
    port: 8888
    protocol: TCP
    targetPort: 8888
    nodePort: 30888
  selector:
    app: jupyter
  sessionAffinity: None
