apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-notebooks-pv
spec:
  storageClassName: hostpath
  hostPath:
    path: /Users/sspaeti/Documents/kubernetes/notebooks
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-notebooks-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi