apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: druid-mm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: druid-middle-manager
  minReplicas: 1
  maxReplicas: 1 #15
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30
