apiVersion: v1
kind: Service
metadata:
  name: druid-broker
  labels:
    app: druid
    component: broker
spec:
  type: NodePort #ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 30082
  selector:
    app: druid
    component: broker
