apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-router
  labels:
    app: druid
    component: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid
      component: router
  template:
    metadata:
      labels:
        app: druid
        component: router
      annotations:
        co.elastic.logs/enabled: 'true'
    spec:
      containers:
        - name: druid
          image: "apache/druid:0.19.0"
          imagePullPolicy: Always
          args: [ "router" ]
          env:
          - name: DRUID_MAXDIRECTMEMORYSIZE
            value: "256m" #"1g"
          - name: DRUID_XMS
            value: "256m" #"2g"
          - name: DRUID_XMX
            value: "256m" #"2g"
          - name: druid_router_http_numConnections
            value: "5" #"50"
          - name: druid_router_http_readTimeout
            value: "PT5M"
          - name: druid_router_managementProxy_enabled
            value: "true"
          - name: druid_router_http_numThreads
            value: "10" #"100"
          - name: druid_router_http_numMaxThreads
            value: "10" #"100"
          envFrom:
            - configMapRef:
                name: druid
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /status/health
              port: 8888
          readinessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: /status/health
              port: 8888
          resources:
            limits:
              cpu: "0.5" #2
              memory: 512Mi #3Gi
