apiVersion: v1
kind: Service
metadata:
  name: druid-router
  labels:
    app: druid
    component: router
spec:
  type: NodePort #ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      nodePort: 30088 #external IP: localhost:30088
  selector:
    app: druid
    component: router
