apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: hostpath
  hostPath:
    path: /Users/sspaeti/Documents/kubernetes/tmp/data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: config-pv
spec:
  storageClassName: hostpath
  hostPath:
    path: /Users/sspaeti/Documents/kubernetes/tmp/config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: config-pvc
spec:
    storageClassName: hostpath
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi